### ISSUE TITLE
Not works on React 16.5.2 get a error message

### ISSUE THREAD

**Issue by borodovisin** [vydimitrov/react-countdown-circle-timer#4]
TypeError
Object(...) is not a function

Can be tested in https://codesandbox.io/s/modern-pine-e8jff, only change the react version to 16.5.2

**Comment by vydimitrov** [comment]
Hey @borodovisin, the library has peer dependency of React 16.8.0 because it is using React hooks. You can read more about it here - https://reactjs.org/docs/hooks-intro.html. Don't downgrade the React version below 16.8.0 and it is going to work as expected.

**Comment by borodovisin** [comment]
@vydimitrov Yeah I see that. Thanks
